#!/usr/bin/env python3

import argparse
from random import randint, seed
from secrets import token_bytes
import functools

from anya import *
from anya.debug import debug_early_init, Logger

def hexint(string: str) -> int:
    return int(string, 16)

def main():
    parser = argparse.ArgumentParser(description="run tests")
    parser.add_argument("-e", dest="ecid", type=hexint, help="ECID to look for and test match")
    parser.add_argument("-k", dest="kbags", action="store_true", help="decrypt the same KBAG many times and test match")
    parser.add_argument("-x", dest="cross", action="store_true", help="decrypt small amounts of KBAGs via AP and SEP sequentially")
    args = parser.parse_args()

    dev = AnyaDevice(ecid=args.ecid)

    debug_early_init(True)

    logger = Logger("MAIN")

    tests = list()

    if args.ecid:
        tests.append(functools.partial(test_ecid, dev, args.ecid))

    if args.kbags:
        tests.append(functools.partial(test_kbags, dev, False))
        tests.append(functools.partial(test_kbags, dev, True))

    if args.cross:
        tests.append(functools.partial(test_cross, dev))

    if not tests:
        logger.error("nothing to test!")
        exit(-1)


    logger.success("running tests")

    try:
        dev.connect()
    except AnyaError as e:
        logger.error("failed to connect: %s" % str(e))
        exit(-1)

    logger.info("found: CPID:%04X CPFM:%02X ECID:%016X" % (
            dev.get_cpid(),
            dev.get_cpfm(),
            dev.get_ecid()
        )
    )

    for test in tests:
        if not test():
            logger.error("something FAILED, exiting")
            dev.disconnect()
            exit(-1)

    dev.disconnect()

    logger.success("DONE")

MIN_KBAG_AMOUNT = 10000
MAX_KBAG_AMOUNT = 30000
NUM_OF_RUNS = 3

def test_kbags(dev: AnyaDevice, sep: bool) -> bool:
    logger = Logger("KBAGS")

    logger.info("starting test")

    if sep:
        try:
            if not dev.ping_sep():
                logger.warning("SEP is not available, skipping")
                return True
        except AnyaError as e:
            logger.error("failed to ping SEP: %s" % str(e))
            return False

        logger.info("will use SEP GID")

    for i in range(NUM_OF_RUNS):
        logger.info("starting run no. %d" % (i + 1))

        seed()
        kbag_count = randint(MIN_KBAG_AMOUNT, MAX_KBAG_AMOUNT)

        kbag = token_bytes(KBAG_SIZE)

        kbags = list()
        for _ in range(kbag_count):
            kbags.append(kbag)

        logger.debug("decrypting same KBAG %d times" % kbag_count)

        try:
            keys = dev.decrypt_kbags(kbags, sep)
        except AnyaError as e:
            logger.error("failed to decrypt: %s" % str(e))
            return False

        logger.debug("comparing...")

        if len(set(keys)) != 1:
            logger.error("OOPS, something doesn't match!")
            return False
        else:
            logger.success("all match!")

    return True

def test_ecid(dev: AnyaDevice, target_ecid: int) -> bool:
    logger = Logger("ECID")

    logger.info("starting test")

    if target_ecid is None:
        logger.warning("no ECID requested, skipping")
        return True

    if target_ecid == dev.get_ecid():
        logger.success("ECIDs match!")
        return True
    else:
        logger.error("ECIDs do not match!")
        return False
    
CROSS_NUM_OF_RUNS = 1000
CROSS_KBAG_MIN_AMOUNT = 100
CROSS_KBAG_MAX_AMOUNT = 500
    
def test_cross(dev: AnyaDevice):
    logger = Logger("CROSS")

    logger.info("starting test")

    try:
        if not dev.ping_sep():
            logger.warning("SEP is not available, failing")
            return False
    except AnyaError as e:
        logger.error("failed to ping SEP: %s" % str(e))
        return False

    for i in range(CROSS_NUM_OF_RUNS):
        logger.info("starting run no. %d" % (i + 1))

        seed()
        kbag_count = randint(CROSS_KBAG_MIN_AMOUNT, CROSS_KBAG_MAX_AMOUNT)

        kbags = list()
        for _ in range(kbag_count):
            kbags.append(token_bytes(KBAG_SIZE))

        sep = (i % 2) == 0

        logger.debug("decrypting %d random KBAGs with %s GID" % (kbag_count, "SEP" if sep else "AP"))

        try:
            dev.decrypt_kbags(kbags, sep)
        except AnyaError as e:
            logger.error("failed to decrypt: %s" % str(e))
            return False

    return True
    
if __name__ == '__main__':
    main()
